apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-cart-pvc
  labels:
    app: redis-cart
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
